### ISSUE TITLE
Precise volume font is hard to read

### ISSUE THREAD

**Issue by Iftuga** [organization/youtube-music-next#10]
When using the precise volume plugin and adjusting the volume level without hovering with the mouse over the image/video so that there is no vignette on top of it, and if the song has a white background, you can not see the volume level
In these two pictures, it is the same corner with and without hovering over the video
I think creating a border or a shadow for the text should fix the issue

![1](https://github.com/organization/youtube-music-next/assets/38592556/a467ee70-7153-4899-b273-ab0ee35e09ed)

![2](https://github.com/organization/youtube-music-next/assets/38592556/3309d260-4eb7-4009-a77b-7a750dce273d)

**Comment by JellyBrick** [comment]
fixed due to a5fe8bc5893daa099ce6ace53ea24fd24d1d0e33

**Comment by Su-Yong** [comment]
![image](https://github.com/organization/youtube-music-next/assets/13764936/bd5d4286-28f5-4c24-8159-c418bf7752b8)
