### ISSUE TITLE
Sidebar buttons shape shift

### ISSUE THREAD

**Issue by Iftuga** [organization/youtube-music-next#12]
When pressing buttons in the sidebar, their on-press visual changes the shape of the button to a rectangle, and then that rectangle stays there, and you can see its corners
It is true for playlists on the sidebar as well

![1](https://github.com/organization/youtube-music-next/assets/38592556/4b4fe2e1-4927-4244-ad26-dac63b67bc9c)

![2](https://github.com/organization/youtube-music-next/assets/38592556/836d27e2-7470-4ada-a70f-70ea3c601a06)

![3](https://github.com/organization/youtube-music-next/assets/38592556/65289430-4a82-4c9c-a771-34468626c271)

**Comment by JellyBrick** [comment]
The cause of this issue appears to be Google's A/B testing 🤦
