### ISSUE TITLE
Prompts update to original Repo

### ISSUE THREAD

**Issue by slh-git** [organization/youtube-music-next#3]
When first time launching prompts an update to the https://github.com/th-ch/youtube-music/releases. Quick change of https://github.com/th-ch/youtube-music/blob/0c45f9850b4cec58e427f201d22e8b4979db1be0/index.js#L408 should do the trick.

**Comment by slh-git** [comment]
Wasn't sure if allowed, remove message if preferred

**Comment by JellyBrick** [comment]
Are you experiencing the same issue in  [v1.20.3](https://github.com/organization/youtube-music-next/releases/tag/v1.20.3)?

This issue should be resolved due to 5cd2e78e884c99b5d246c7cab8ff9b15be537cac.
