### ISSUE TITLE
Taskbar mediacontrol plugin has no icons 

### ISSUE THREAD

**Issue by Iftuga** [organization/youtube-music-next#30]
![1](https://github.com/organization/youtube-music-next/assets/38592556/2c5e6011-16a1-4641-aafd-0bae2feda54b)

**Comment by Iftuga** [comment]
Still no icons in 2.0.3 💀

**Comment by JellyBrick** [comment]
![image](https://github.com/organization/youtube-music-next/assets/16558115/8fe310d9-a8cf-45f5-b280-05de9a778902)
Try deleting `%appdata%\YouTube Music\icons` and running YTM-next again.
![image](https://github.com/organization/youtube-music-next/assets/16558115/37d029a8-2b24-497c-956c-1ef44a0f6f11)

**Comment by Iftuga** [comment]
I have YouTube Music folders in ```AppData\Roaming``` and ```AppData\Local\Programs``` and both of them do not have "icons" folder 🤔

![image](https://github.com/organization/youtube-music-next/assets/38592556/5b9aa877-bb0b-48f1-8d2f-d9c70de5441f)

**Comment by JellyBrick** [comment]
Have you tried uninstalling and reinstalling the YTM-next?

**Comment by Iftuga** [comment]
Yes, just tried a clean install
Deleted both folders with the program itself and the folder that has a config file in it
Still no icons

**Comment by JellyBrick** [comment]
Use https://github.com/th-ch/youtube-music instead (this issue is fixed there)
