### ISSUE TITLE
Tray Enabled + app hidden bug

### ISSUE THREAD

**Issue by Iftuga** [organization/youtube-music-next#5]
Right now it seems to work exactly the same as Tray Enabled + app visible
In both cases app disappears from task bar after closing it but stays after minimizing it
I am using Windows 11

**Comment by JellyBrick** [comment]
- `Tray Enabled + App Visible`: When the application starts, display a window and register it to the tray
- `Tray Enabled + App Hidden`: When the application starts, register it to the tray (without displaying any window)

**Comment by Iftuga** [comment]
I can still see the app window on application start even with Tray Enabled + App Hidden option selected

**Comment by Iftuga** [comment]
I can see on my end that it is not consistent
You can try to maximize and minimize the window and restart the application a couple of times
I can not figure out under which conditions it hides itself on start correctly and why it fails to do so sometimes

**Comment by JellyBrick** [comment]
Is this issue still happening in `2.0.3`?

**Comment by Iftuga** [comment]
Yes, clean install, each time I press the restart app button or exit and start it manually, the app window appears on my desktop

**Comment by Iftuga** [comment]
If I restart the PC and "start at login" is enabled, then it is hidden to tray correctly
But if I restart or launch it manually, then not

**Comment by JellyBrick** [comment]
Use https://github.com/th-ch/youtube-music instead (this issue is fixed there)
