### ISSUE TITLE
Please consider providing non portable Windows exe also

### ISSUE THREAD

**Issue by Iftuga** [organization/youtube-music-next#8]
Love the fork so far, great job
Regarding the issue itself, it is more convenient for me when the actual exe file has a constant location so that I can use it with a split-tunnel VPN or some other application that requires a path to the exe file

**Comment by JellyBrick** [comment]
What do you mean by `non-portable Windows exe`?

YTM-next also offers an installable version.
https://github.com/organization/youtube-music-next/releases/download/v1.20.3/YouTube-Music-Setup-1.20.3.exe

**Comment by Iftuga** [comment]
Ah, I see, thanks, I did not click on the "see all assets" button, so I did not notice installable version
